import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/index.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>REST API UI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome!
        </h1>

        <p className={styles.description}>
          REST API frontend
          <code className={styles.code}>aronhd</code>
        </p>

        <div className={styles.grid}>
          <a href="/" className={styles.card}>
            <h2>0 &rarr;</h2>
          </a>

          <a href="/" className={styles.card}>
            <h2>1 &rarr;</h2>
          </a>

          <a
            href="/"
            className={styles.card}
          >
            <h2>2 &rarr;</h2>
          </a>

          <a
            href="/"
            className={styles.card}
          >
            <h2>3 &rarr;</h2>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://aronhd.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Built by aronhd{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
